- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
- name: adding repo
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
- name: Install Grafana
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - grafana
- name: Make sure a grafana-server service is running
  systemd:
    state: started
    enabled: yes
    name: grafana-server
# Copy Grafana Configs 
- name: Create grafana main configuration file
  template:
    src: grafana.ini.j2
    dest: "{{ config_dir }}/grafana.ini"
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana-server

- name: Install a list of packages
  grafana_plugin:
    name: "{{ item }}"
    version: latest
    state: present
  with_items: "{{ plugins }}"
  notify: restart grafana-server